project:
  type: book
  output-dir: docs

book:
  title: "Community detection tutorial"
  author: "Ana Miller-ter Kuile"
  search: true
  repo-url: https://github.com/an-bui/community_detection_tutorial
  chapters:
    - index.qmd
    - 01_accounting-for-imperfect-detection.qmd
    - 02_computing-indices.qmd
    - 03_community-stability-environment.qmd
    - 04_imperfect-detection.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



