project:
  type: book
  output-dir: docs

book:
  title: "Community detection tutorial"
  author: "Ana Miller-ter Kuile"
  date: "5/10/2024"
  chapters:
    - index.qmd
    - part: 01_description.qmd
      chapters:
      - 01.2_computing-indices.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



