# Preface {.unnumbered}

## Description

This is a modeling tutorial for the supplement for Miller-ter Kuile et al. "If you’re rare, should I care? How imperfect detection changes relationships between biodiversity and global change drivers". 

The purpose of this tutorial is to provide a detailed description of the modeling approaches used in the paper along with examples of the models in action on both simulated and real datasets.

## Tools you'll need

All models are Bayesian models run in R and JAGS. You will need these programs to run these models.

[Download R](https://cran.rstudio.com/)

(We also recommend [RStudio](https://posit.co/download/rstudio-desktop/))

[Download JAGS](https://sourceforge.net/projects/mcmc-jags/files/)

Other options are available for running Bayesian models, including [Stan](https://mc-stan.org/) and [NIMBLE](https://r-nimble.org/). There is less flexibility but great usability for users of any experience level for running multi-species occupancy models in the package [`spOccupancy`](https://doserlab.com/files/spoccupancy-web/). Given the incorporation of uncertainty in the regression models we developed, it would be challenging to run them in programs with built-in regression model functions, but they can be built in any Bayesian modeling language/program (JAGS, Stan, BUGS, NIMBLE).

## Model description

We employed a two-step modeling process (Figure 1).

![Figure 1: Depiction of the two-step modeling process, including A) accounting for imperfect detection using a multi-species occupancy or abundance model and B) using derived quantitites of community change along with their uncertainty in a regression examining current and past environmental drivers of change.](pictures/DAG_v2.jpg)

### A) Multi-species model accounting for imperfect detection

This model links observed abundance or presence-absence of species in a community to detection probabilities to generate a latent "true" abundance or occupancy for each species in each site in each year. We used this model to then generate metrics of biodiversity. We built these models based on previous model developments for accounting for imperfect detection in community datasets [@dorazio2006].

### B) Regression model with environmental covariates

This model incorporates mean and variance of biodiversity metrics from the model in A) into a regression examining the effects of environmental covariates on biodiversity. This model employs a stochastic antecedent modeling (SAM) framework [@ogle2015] to allow environmental covariates to have immediate and lagged responses.

## Outline

In the following pages, we will walk you through the model formulation as well as model code demonstrating the modeling framework.

1.  **Accounting for imperfect detection** walks through accounting for imperfect detection in a multi-species model
2.  **Computing indices of biodiversity** illustrates how posterior samples for latent occupancy or abundance from the models for imperfect detection can be used to calculate multiple indices of biodiversity either inside Bayesian modeling software as derived quantities or through functions available in a variety of R packages
3.  **Evaluating biodiversity in relation to environmental variables** shows how to take these derived values of biodiversity and uncertainty around them and use them in a regression that allows covariates to have immediate and lagged effects on biodiversity metrics
